#!/bin/sh
DIR=$(cd "$(dirname "$0")" && pwd)
export LD_LIBRARY_PATH="$DIR/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export PULSE_SERVER="${PULSE_SERVER:-unix:/var/run/pulse/native}"
exec "$DIR/shairport-sync" -c "$DIR/shairport-sync.conf" "$@"
