general = {
  name = "Gigawatt";
  interpolation = "basic";
  output_backend = "pa";
  ignore_volume_control = "no";
  port = 5000;
};
sessioncontrol = {
  allow_session_interruption = "yes";
  session_timeout = 120;
};
metadata = {
  enabled = "yes";
  include_cover_art = "no";
  pipe_name = "/tmp/gigawatt-airplay.meta";
  pipe_timeout = 5000;
};
pa = {
  application_name = "Gigawatt AirPlay";
};
